---
# handlers file for pxeboot

## the name will be the same name as the tasks/configure.yml notify
- name: restart networking service
  service:
    name: networking
    state: restarted

- name: restart isc-dhcp-server service
  service:
    name: isc-dhcp-server
    state: restarted

- name: restart tftpd-hpa service
  service:
    name: tftpd-hpa
    state: restarted

- name: reload NAT
  shell: sysctl -p /etc/sysctl.conf
