---
# handlers file for pxeboot

## the name will be the same name as the tasks/configure.yml notify

- name: restart isc-dhcp-server service
  service:
    name: isc-dhcp-server
    state: restarted

- name: restart networking service
  service:
    name: networking
    state: restarted
