---
# tasks file for pxeboot
- name: Upload DHCP configure and restart DHCP service
  copy:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
   - restart isc-dhcp-server service
## the nofify name will be the same name as the handler's name

- name: Upload DHCP interface config
  copy:
    src: isc-dhcp-server
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Upload Ethernet 2nd adapter  and restart Networking service
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
   - restart networking service


- name: Upload tftp file
  copy:
    src: tftpd-hpa
    dest: /etc/default/tftpd-hpa
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Upload inetd.conf file and restart tftp  service
  copy:
    src: inetd.conf
    dest: /etc/inetd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
   - restart tftpd-hpa service

