---
# tasks file for pxeboot
- name: Install PXEboot  packages
  apt: name={{item}} state=installed update_cache=true
  with_items:
  - htop
  - tree
  - open-vm-tools
  - isc-dhcp-server
  - apache2
  - tftpd-hpa
  - inetutils-inetd
  when: ansible_os_family == "Debian"
